name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy image
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Image
        run: |
          docker build -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

      - name: Gcloud Authentication
        run: |
          gcloud auth configure-docker -q

      - name: Deploy Image to Container Registry
        run: |
          docker push asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME --image asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --allow-unauthenticated \
          --memory 512M \
          --region asia-southeast1 \
          --max-instances 10 \
          --port 3000